import { styleMerge } from "@/utils/cn";
import "./globals.css";
import { Manrope } from "next/font/google";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

const manp = Manrope({
  subsets: ["latin"],
  display: "swap",
});

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <head>
        <link
          href="https://api.fontshare.com/v2/css?f[]=satoshi@1,2&display=swap"
          rel="stylesheet"
        />
      </head>
      <body
        className={styleMerge(
          "bg-[#f4f0e1] text-white font-medium",
          manp.className
        )}
      >
        {children}
      </body>
    </html>
  );
}
